spring:
  application:
    name: gateway-service
  config:
    import: "optional:configserver:"
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/test
  cloud:
    config:
      discovery:
        service-id: config-service
        enabled: true
    gateway:
      default-filters:
        - TokenRelay=
      routes:
        - id: checkout-service
          uri: lb://checkout-service
          predicates:
            - Path=/checkout/**
          filters:
            - AddRequestHeader=X-Custom-Header, Gateway-Service
            - AddResponseHeader=X-Custom-ResponseHeader, Gateway-Service
        - id: products-service
          uri: lb://products-service
          predicates:
            - Path=/products/**

server:
  port: 8085

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    fetchRegistry: true
    registerWithEureka: true
    instance-info-replication-interval-seconds: 10
    initial-instance-info-replication-interval-seconds: 5
  instance:
    hostname: localhost
    preferIpAddress: false

logging:
  level:
    com:
      netflix: DEBUG
    org:
      springframework:
        cloud: 
          netflix:
            eureka: DEBUG