server:
  port: 8085

spring:
  config:
    import: "optional:configserver:"
  application:
    name: gateway-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/test
  cloud:
    config:
      discovery:
        service-id: config-service
        enabled: true
    gateway:
      routes:
        - id: checkout-service
          uri: lb://checkout-service
          predicates:
            - Path=/checkout/**
          filters:
            - AddRequestHeader=X-Custom-Header, Gateway-Service
            - AddResponseHeader=X-Custom-ResponseHeader, Gateway-Service
        - id: products-service
          uri: lb://products-service
          predicates:
            - Path=/products/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
      register-with-eureka: true
      fetch-registry: true
