version: '3.8'

services:
  eureka-server:
    build: eureka-server/
    mem_limit: 512m
    ports:
      - "8761:8761"    
  config-server:
    build: config-server/
    mem_limit: 512m
    depends_on:
      - eureka-server
    ports:
      - "8889:8889"    
  gateway:
    build: gateway/
    mem_limit: 512m
    depends_on:
      - config-server
    ports:
      - "8085:8085"    
  checkout-service:
    build: checkout-service/
    mem_limit: 512m
    ports:
      - "8081:8090"    
  notification-service:
    build: notification/
    mem_limit: 512m
    ports:
      - "8083:8090"    
  payments-service:
    build: payments/
    mem_limit: 512m
    depends_on:
      - config-server
    ports:
      - "8082:8090"    
  products-service:
    build: products-service/
    mem_limit: 512m
    ports:
      - "8084:8090"    

  rabbitmq:
    image: rabbitmq:4.0-management
    mem_limit: 512m
    ports:
      - "5672:5672"
      - "15672:15672"    
  keycloak:
    image: quay.io/keycloak/keycloak:25.0.6
    mem_limit: 512m
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    command:
      start-dev    
  zipkin:
    image: openzipkin/zipkin    
    ports:
      - "9411:9411"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.2
    environment:
      - discovery.type=single-node      
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"    

  kibana:
    image: docker.elastic.co/kibana/kibana:8.15.2
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - xpack.security.enabled=false
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  logstash:
    image: docker.elastic.co/logstash/logstash:8.15.2    
    ports:
      - "5044:5044"
      - "9600:9600"
    volumes:
      - /Users/michaelrodriguez/springboot/logstash-8.15.2/config:/usr/share/logstash/config
      - /Users/michaelrodriguez/springboot/logs:/usr/share/logstash/logs
    depends_on:
      - elasticsearch    

volumes:
  es_data:
    driver: local
  logs_volume:
    driver: local